[pytest]
minversion = 9.0
addopts = -v -ra
         --alluredir=allure-results
testpaths = tests
python_files = test_*.py

markers =
    slow: проверки, которые могут выполняться долго из-за ответа ИИ
    negative: негативые проверки
    positive: позитивные проверки
